### ISSUE TITLE
Clients show 0 apps after restart

### ISSUE THREAD

**Issue by knitty-cat** [munkireport/applications#10]
Hi,

im having some strange behavior with the app module.
I enabled it and reinstalled the clients. 
I use it to keep track of Premiere Pro installations.
Some if them (four at the moment) show their apps for about 4 days. Then their app module shows 0. I always have to reinstall those clients.

Any known Problems?
Why only those four clients? (Other clients in there IP address-area work)

thx in advance,
alex

**Comment by tuxudo** [comment]
This may be because Spotlight is still indexing the applications on the client. On the client backend, Spotlight is used to identify all the applications on the client.
