### ISSUE TITLE
Add collection of app CFBundleVersion value

### ISSUE THREAD

**Issue by apizz** [munkireport/applications#11]
Currently, code utilizes app records from `system_profiler`, but this uses the `CFBundleShortVersionString` key value by default.  In some apps, like Zoom and Sublime Text, the `CFBundleVersion` key value is more accurate.

Given the module collects the path of each app, adding a stop to recursively append `/Contents/Info.plist` to the app path and reading the `CFBundleVersion` would be a helpful addition.

Since the current column is listed as 'version' I'm not sure what would make the most sense to name this additional column of data.

**Comment by tuxudo** [comment]
Should be resolved with PR #14 and module version v2.5

**Comment by apizz** [comment]
Can confirm
