### ISSUE TITLE
"App Versions Report" not showing clients

### ISSUE THREAD

**Issue by nard-dogg** [munkireport/applications#18]
Hello,

This is my first time setting up MunkiReport and local server, I currently have it successfully reporting reports on other modules, however the "App Versions Report" is displaying "No data available in table" for each application even though I can confirm that the applications are successfully installed.

It appears as though the module is either not pulling the information or outputting it correctly.

Please can anyone advise?

Kind regards,

**Comment by tuxudo** [comment]
The App Versions Report is a part of the `inventory` module. That module requires Munki to be installed and properly running on the client. In addition to Munki, you have to specify what applications you want to track using the `apps_to_track` array in your .env file

**Comment by nard-dogg** [comment]
Thank you @tuxudo for your response and resolve.

Once I installed Munki and ran the following command:

"sudo /usr/local/munki/managedsoftwareupdate -vv --checkonly"


I then ran "sudo /usr/local/munkireport/munkireport-runner" on the client workstation which populated the "App Version Reports" on my local server.

**Comment by tuxudo** [comment]
Happy to hear you got it work!
